name: PyTest
on: pull_request
jobs:
  pre-commit:
    name: Run pre-commit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Install poetry, pre-commit and the dynamic-versioning plugin
        run: |
          pipx install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          pipx install pre-commit
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'poetry'
      - run: poetry install
      - name: Run pre-commit tests
        run: pre-commit run --from-ref HEAD^ --to-ref HEAD
  pytest:
    name: Run the application's tests with PyTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Install poetry, pre-commit and the dynamic-versioning plugin
        run: |
          pipx install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          pipx install pre-commit
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'poetry'
      - run: poetry install
      - name: Run PyTest
        run: poetry run pytest -v
