name: Publish to PyPi
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    name: Publish package to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install poetry and the dynamic-versioning plugin
        run: |
          pip install --user poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Cache poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashfiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashfiles('**/poetry.lock') }}
      - name: Set poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Setup environment
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Publish to PyPi via Poetry
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
